<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Paul Jones</Authors>
    <Company>ne1410s</Company>
    <Description>Delivers opinionated, Roslyn-based static code analysis</Description>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageTags>Roslyn analysis static code analyze analyse</PackageTags>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <IncludeBuildOutput>False</IncludeBuildOutput>
    <IncludeSymbols>False</IncludeSymbols>
    <NoPackageAnalysis>True</NoPackageAnalysis>
    <PackageId>ne1410s.$(AssemblyName)</PackageId>
    <PackageIcon>ICON.png</PackageIcon>
    <PackageIconUrl>ICON.png</PackageIconUrl>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/ne1410s/Analyse</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/ne1410s/Analyse</RepositoryUrl>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Title>$(AssemblyName)</Title>
    <VersionPrefix>1.0.1</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" Visible="false" />
    <None Include="../../LICENSE" Pack="true" PackagePath="/" Visible="false" />
    <None Include="../../ICON.png" Pack="true" PackagePath="/" Visible="false" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Analyse.props" Pack="true" PackagePath="build" />
    <None Include="../Analyse.globalconfig" Pack="true" PackagePath="content" />
    <None Include="../stylecop.json" Pack="true" PackagePath="content" />
  </ItemGroup>
  
</Project>
