<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Paul Jones</Authors>
    <Company>ne1410s</Company>
    <Description>Delivers opinionated, Roslyn-based static code analysis</Description>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageTags>Roslyn analysis static code analyzer</PackageTags>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <IncludeBuildOutput>False</IncludeBuildOutput>
    <IncludeSymbols>False</IncludeSymbols>
    <NoPackageAnalysis>True</NoPackageAnalysis>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/ne1410s/Analyse</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/ne1410s/Analyse</RepositoryUrl>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Title>$(AssemblyName)</Title>
    <VersionPrefix>1.0.9</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <Visible>False</Visible>
    </None>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
      <Visible>False</Visible>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="Analyse.props" Pack="true" PackagePath="build" />
    <None Include="../stylecop.json" Pack="true" PackagePath="content" />
    <Content Include="../.analyzerconfig" Pack="true" PackagePath="content" />
  </ItemGroup>
  
</Project>
