<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Authors>Paul Jones</Authors>
    <Company>ne1410s</Company>
    <Description>Delivers opinionated, Roslyn-based static code analysis</Description>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <PackageTags>Roslyn analysis static code analyzer</PackageTags>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <IncludeBuildOutput>False</IncludeBuildOutput>
    <IncludeSymbols>False</IncludeSymbols>
    <NoPackageAnalysis>True</NoPackageAnalysis>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/ne1410s/Analyse</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/ne1410s/Analyse</RepositoryUrl>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Title>$(AssemblyName)</Title>
    <VersionPrefix>1.0.4</VersionPrefix>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <None Include="Analyse.props" Pack="true" PackagePath="build" />
    <None Include="stylecop.json" Pack="true" PackagePath="content" />
    <Content Include=".analyzerconfig" Pack="true" PackagePath="content" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Roslynator.Analyzers" Version="4.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="4.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Roslynator.Formatting.Analyzers" Version="4.1.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SonarAnalyzer.CSharp" Version="8.49.0.57237">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
</Project>
