name: test
on:
  pull_request:
    paths:
    - source/**
  workflow_call:
jobs:
  run_tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./source
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Add local packages source
      env:
        READ_REPO_PACKAGES: ${{ secrets.READ_REPO_PACKAGES }}
      run: dotnet nuget add source --name ne1410s --username ne1410s --password "${{ env.READ_REPO_PACKAGES }}" --store-password-in-clear-text "https://nuget.pkg.github.com/ne1410s/index.json"
    - name: Restore tools
      run: dotnet tool restore
    - name: Build for release (failing build warnings)
      run: dotnet build -c Release --no-incremental /warnaserror
